Class PXW.DEV.BNF.Elements.SQL Extends PXW.DEV.BNF.Element
{

/*
property AliasName as list of PXW.DEV.BNF.Elements.SQL;
property AsClause as list of PXW.DEV.BNF.Elements.SQL;
property TableAsClause as list of PXW.DEV.BNF.Elements.SQL;
property DerivedColumn as list of PXW.DEV.BNF.Elements.SQL;
property SelectList as list of PXW.DEV.BNF.Elements.SQL;
property SelectSublist as list of PXW.DEV.BNF.Elements.SQL;
property ColumnName as list of PXW.DEV.BNF.Elements.SQL;
*/
}
